### ISSUE TITLE
webserial_scraper does not contain any element

### ISSUE THREAD

**Issue by Tantusar** [Curetix/webfiction-scraper#6]
I'm attempting to install this using Poetry, but it throws an `[irrelevant parent directories]\webfiction-scraper-main\webserial_scraper does not contain any element` error. The `pyproject.toml` file mentions `webserial_scraper` as one of its includes but this term appears nowhere else in the project's filenames or file contents. Replacing this term with `webfictionscraper.py` eliminates the error but does not seem to result in the project being installed as a command.

Python 3.12.0, Poetry 1.8.2, Windows 10 Home 22H2 (19045.4046), PowerShell 5.1.19041.4046

**Comment by Curetix** [comment]
Thanks for pointing this out, there was some outdated stuff in the `pyproject.toml`. Also, it seems like you need to use `pip install .` to install this package as a global command. Alternatively, using Poetry, you can run `poetry run webfictionscraper`. I will update the instructions accordingly.
